### PR TITLE
JSON Parsing

### PR DESCRIPTION
**Pull request by vipulnsward**
The current way makes the loading of data lengthy, adding caching in preferences would help
But was unsure as to when the URL's should be updated after some timeout, to retrieve fresh data.

### CODE REVIEW

**Comment by dmorley** [comment]
My poduptime app is made with appinventor is is total crap, it might be cool if you two have the time to add that very basic, find a pod functionality to this application!

**Comment by vipulnsward** [comment]
On Dec 3, 2011 8:57 PM, "David Morley" <
reply@reply.github.com>
wrote:

> My poduptime app is made with appinventor is is total crap, it might be
> cool if you two have the time to add that very basic, find a pod
> functionality to this application!

David i had asked you where the code was. I dint happen to find it.

**Comment by dmorley** [comment]
sorry i forgot, all there now https://github.com/diasporg/Poduptime-Android

**Comment by voidcode** [comment]
Looks good Vipulnsward ;)
I am new to merged and git, how do I merged your to commits into my master branch?
https://github.com/voidcode/Diaspora-Webclient/network

**Comment by vipulnsward** [comment]
On Dec 4, 2011 12:07 PM, "Voidcode" <
reply@reply.github.com>
wrote:

> Looks good Vipulnsward ;)
> I am new to merged and git, how do I merged your to commit into my master
> branch?

Try this http://help.github.com/send-pull-requests/

The page provides 3 ways to do it,the last one being directly accepting via
github merge button on pull requests tab.

**Comment by vipulnsward** [comment]
On Dec 4, 2011 2:48 AM, "David Morley" <
reply@reply.github.com>
wrote:

> sorry i forgot, all there now
> https://github.com/diasporg/Poduptime-Android

Ok so,should i create a mock up app,for you in eclipse. I l need to do that
from scratch? That way the appinventor shortcomings wont hurt,as also
there's currently no way to export your code directly to eclipse,so i l
need to do it from scratch.

**Comment by voidcode** [comment]
Now I have merged the SettingActivity.java
But if I make a clone of my master,
Then Eclipse make an error, this is because git has added.

<<<<<<< HEAD
import android.content.res.Configuration;
import android.os.Bundle;

# import android.view.KeyEvent;

import android.os.Bundle;
import android.util.Log;

> > > > > > > c7c776c4bac93c9538f07b0da9feccf776509ab6

I do not know why it does this?

**Comment by voidcode** [comment]
Patch is now push to the Android market.
Thank you very much for the help ;-)

**Pull request closed without merging**
